<a href="https://colab.research.google.com/github/KennyThinh/pytorch/blob/main/01_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.__version__

'1.8.0+cu101'

1.   Init tensor

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32, device = device)
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')
torch.float32
cuda:0
torch.Size([2, 3])


In [4]:
x = torch.empty(size=(3,3)) # random
x = torch.zeros((3,3))
x = torch.ones((3,3))
x = torch.eye(3,3)
x = torch.arange(start=0, end =10, step = 1)
x = torch.linspace(start = 0, end = 1,steps = 10)
print(x)

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [5]:
x = torch.rand(size=(3,3)) # values are uniform distribution
x = torch.empty(size=(3,3)).uniform_(0,1)
print(x)

x = torch.empty(size=(2,5)).normal_(mean=0, std=1) #normal distribution
print(x)

tensor([[0.9172, 0.4362, 0.8004],
        [0.7643, 0.9213, 0.7260],
        [0.2112, 0.2593, 0.4131]])
tensor([[ 0.6618, -1.0987, -0.8850, -0.9358,  0.3156],
        [-2.6305, -0.8108,  0.6399,  0.0691, -0.5711]])


In [6]:
x = torch.diag(torch.ones(3)) # similar to eye but we can use any values on the diag
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [7]:
# initialize and convert tensors
my_tensor = torch.arange(3) # tensor([0, 1, 2])
my_tensor.bool() #tensor([False,  True,  True])
my_tensor.short() # int16
my_tensor.half() #float16 for 20xx gpu series
my_tensor.long() # int64 (*)
my_tensor.float() #float32 (*)
my_tensor.double() #float64 

# convert btw numpy and tensor
my_tensor_np = my_tensor.numpy()
my_tensor_torch = torch.from_numpy(my_tensor_np)
my_tensor_np, my_tensor_torch,

(array([0, 1, 2]), tensor([0, 1, 2]))

2.   Tensor math and comparision


In [8]:
x  = torch.tensor([1,2,3])
y = torch.tensor([9, 8, 7])

#add
z = x + y 
z = torch.add(x,y)
z = x.add(y)

# subtraction
z = x - y 
z = torch.subtract(x,y)
z = x.subtract(y)

# multiply
z = x*y

# divide
z = torch.true_divide(x,y)

#compare
z = x < 0

#inplace 
t = torch.zeros(3)
t.add_(x) 
t += x # t = t+x is not inplace


#power 
z = torch.pow(x, 2)
z = x ** 2

# special
values, indexes = torch.max(x, dim=0)
values, indexes = torch.min(x, dim=0)
z = torch.abs(x)
z = torch.mean(x.float(), dim=0)
z = torch.clamp(x, min = 2, max = 2) # values less than 1 will be 1, larger than 5 will be 5
z = torch.tensor([1,0,1,1,1,1], dtype = torch.bool).any() #true if there is any true in the tensor
z = torch.tensor([1,0,1,1,1,1], dtype = torch.bool).all() #true if all values are true in the tensor
print(z)

tensor(False)


In [9]:

#matrix multiplication
x1 = torch.rand((2,4))
x2 = torch.rand((4,3))
z = torch.mm(x1, x2)
z = x1.mm(x2)

# batch matrix multiplication
batch = 10
n= 3
m = 5
p = 3
x1 = torch.rand((batch, n, m))
x2 = torch.rand((batch, m, p))
z = torch.bmm(x1, x2) # (batch, n, p)

#matrix exponentiation
z = torch.rand(4,4)
z.matrix_power(100)

# dot product
z = torch.dot(x,y)
print(x*y)

print(z)

tensor([ 9, 16, 21])
tensor(46)


3. Tensor indexing

In [10]:
x = torch.rand((10, 25))
print(x[0].shape, x[0,:].shape)
print(x[2,0:24])
print(x[[2,5,8],:]) # row index is a list
print(x[[2,5,8],[1,2,3]]) # row index, column index is a list

torch.Size([25]) torch.Size([25])
tensor([0.8452, 0.6110, 0.3383, 0.9151, 0.2701, 0.7589, 0.3199, 0.8626, 0.7213,
        0.2712, 0.9179, 0.9953, 0.5664, 0.7839, 0.4330, 0.5027, 0.2608, 0.2470,
        0.1939, 0.2913, 0.2046, 0.8587, 0.3754, 0.5088])
tensor([[0.8452, 0.6110, 0.3383, 0.9151, 0.2701, 0.7589, 0.3199, 0.8626, 0.7213,
         0.2712, 0.9179, 0.9953, 0.5664, 0.7839, 0.4330, 0.5027, 0.2608, 0.2470,
         0.1939, 0.2913, 0.2046, 0.8587, 0.3754, 0.5088, 0.2124],
        [0.2909, 0.6764, 0.1283, 0.3944, 0.2936, 0.1601, 0.5348, 0.6529, 0.3835,
         0.9138, 0.4479, 0.6131, 0.7416, 0.0898, 0.7046, 0.0770, 0.0565, 0.7338,
         0.1534, 0.4811, 0.3713, 0.2264, 0.4930, 0.3334, 0.3165],
        [0.7848, 0.1856, 0.0207, 0.1551, 0.3179, 0.6025, 0.0915, 0.5630, 0.4094,
         0.2206, 0.6937, 0.2291, 0.5651, 0.5992, 0.8317, 0.3768, 0.2959, 0.7047,
         0.4806, 0.5921, 0.5086, 0.3289, 0.1013, 0.4629, 0.1199]])
tensor([0.6110, 0.1283, 0.1551])


In [11]:
x = torch.rand((10,25))
x[(x>0.2) & (x<0.5)]
print(torch.where(x>0,1,0))
x.unique()
x.ndimension()
x.numel() # how many number

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1]])


250

4.   Reshape

In [12]:
x = torch.arange(9)
print(x.view(3,3))
print(x.reshape(3,3))
y = x.view(3,3).t()
print(y.contiguous().view(9)) # need contiguous() before view() 

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [21]:
x1 = torch.arange(9)
print(x1.view(-1))
print(x1.unsqueeze(0).shape) #add 1 dimension in front
print(x1.unsqueeze(1).shape) #add 1 dimension in back
print(x1.unsqueeze(0).unsqueeze(0).shape) # (1,1,9)
print(x1.unsqueeze(0).unsqueeze(0).squeeze(0).shape) # (1,9)
x = torch.rand((10, 2, 4))
print(x.view(batch, -1).shape) #10, 8, all the remanining shape will be flattern

print(x.permute(0,2,1).shape) # rearrange column of x --> 10, 4, 2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
torch.Size([1, 9])
torch.Size([9, 1])
torch.Size([1, 1, 9])
torch.Size([1, 9])
torch.Size([10, 8])
torch.Size([10, 4, 2])
