<a href="https://colab.research.google.com/github/KennyThinh/pytorch/blob/main/Extra01_CalculateMeanAndStd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torchvision.datasets as datasets
from tqdm import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
train_set = datasets.CIFAR10(root="ds/", transform=transforms.ToTensor(), download=True)
train_loader = DataLoader(dataset=train_set, batch_size=64, shuffle=True)

def get_mean_std(loader):
    # var[X] = E[X**2] - E[X]**2
    channels_sum, channels_sqrd_sum, num_batches = 0, 0, 0

    for data, _ in tqdm(loader):
        channels_sum += torch.mean(data, dim=[0, 2, 3])
        channels_sqrd_sum += torch.mean(data ** 2, dim=[0, 2, 3])
        num_batches += 1

    mean = channels_sum / num_batches
    std = (channels_sqrd_sum / num_batches - mean ** 2) ** 0.5

    return mean, std


mean, std = get_mean_std(train_loader)
print(mean)
print(std)


Extracting ds/cifar-10-python.tar.gz to ds/


100%|██████████| 782/782 [00:05<00:00, 136.74it/s]

tensor([0.4914, 0.4822, 0.4465])
tensor([0.2470, 0.2435, 0.2616])


In [11]:
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2470, 0.2435, 0.2616))])
train_set = datasets.CIFAR10(root="ds/", transform=transform, download=True)
train_loader = DataLoader(dataset=train_set, batch_size=64, shuffle=True)
mean, std = get_mean_std(train_loader)
print(mean)
print(std)

Files already downloaded and verified


100%|██████████| 782/782 [00:08<00:00, 87.30it/s]

tensor([ 2.0441e-05, -1.4885e-04,  8.0527e-05])
tensor([1.0003, 1.0001, 1.0001])


**MNIST**

In [4]:
train_set = datasets.MNIST(root="/mnist", transform = transforms.ToTensor(), download = True) #default train=True, so this is only the train set
train_loader = DataLoader(dataset=train_set, batch_size=64, shuffle=True)
mean, std = get_mean_std(train_loader)
print(mean)
print(std)


Extracting /mnist/MNIST/raw/train-images-idx3-ubyte.gz to /mnist/MNIST/raw




Extracting /mnist/MNIST/raw/train-labels-idx1-ubyte.gz to /mnist/MNIST/raw

Failed to download (trying next):
HTTP Error 503: Service Unavailable




Extracting /mnist/MNIST/raw/t10k-images-idx3-ubyte.gz to /mnist/MNIST/raw



/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:502: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:143.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
  0%|          | 0/938 [00:00<?, ?it/s]

Extracting /mnist/MNIST/raw/t10k-labels-idx1-ubyte.gz to /mnist/MNIST/raw

Processing...
Done!


100%|██████████| 938/938 [00:04<00:00, 214.00it/s]

tensor([0.1307])
tensor([0.3081])


In [9]:
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307), (0.3081))])
train_set = datasets.MNIST(root="/mnist", transform = transform, download = True)
train_loader = DataLoader(dataset=train_set, batch_size=64, shuffle=True)
mean, std = get_mean_std(train_loader)
print(mean)
print(std)

100%|██████████| 938/938 [00:07<00:00, 118.77it/s]

tensor([-0.0001])
tensor([1.0000])
